### ISSUE TITLE
error in dependency  

### ISSUE THREAD

**Issue by myeghaneh** [nsaphra/AMRICA#6]
I am trying to use your repo, unfortunately for installing dependency I faced with an error  

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\moha\Anaconda3\envs\argenvv01\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\moha\\AppData\\Local\\Temp\\pip-install-ev67ewnx\\argparse-config\\setup.py'"'"'; __file__='"'"'C:\\Users\\moha\\AppData\\Local\\Temp\\pip-install-ev67ewnx\\argparse-config\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\moha\AppData\Local\Temp\pip-pip-egg-info-6k9vd6ut'
         cwd: C:\Users\moha\AppData\Local\Temp\pip-install-ev67ewnx\argparse-config\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\moha\AppData\Local\Temp\pip-install-ev67ewnx\argparse-config\setup.py", line 2, in <module>
        from argparse_config import __version__
      File "C:\Users\moha\AppData\Local\Temp\pip-install-ev67ewnx\argparse-config\argparse_config\__init__.py", line 4, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

as the repo is for 4 years ago, is there any way that i use it?

**Comment by nsaphra** [comment]
What version of python are you using? Can you virtualenv super old?
